//
// Test-case for string matching
//

.type String <: symbol

.decl inputData   (t:String) // fuzzable relation
.decl pattern   (t:String) // fuzzable relation
.decl outputData  (t:String) // fuzzable relation
.output outputData  ()

outputData(x) :- pattern(y), inputData(x), match(y, x).

inputData("aaaa").
inputData("a").
inputData("abba").
inputData("bcab").
inputData("bdab").
inputData("cdab").

pattern("a.*").
pattern("b.*").
pattern("b.*[").
