
.decl lim(n : number) // fuzzable relation
.input lim()

.decl naturals(n : number) // fuzzable relation
naturals(0).
naturals(n+1) :- naturals(n), n < s, lim(s).

// Binomial Coefficients
.decl choose(n : number, k : number, v : number) // fuzzable relation
choose(n, n, 1) :- naturals(n).
choose(n, (n - k), v) :- choose(n, k, v).
choose(n+1, k+1, v1 + v2) :- choose(n, k, v1), choose(n, k+1, v2).

.decl catalan(n : number, v: number) // fuzzable relation
.output catalan()
catalan(n, v) :- choose(2*n, n, c), naturals(v), v=c/(n+1).


