
.decl A (X:number) // fuzzable relation
.decl B (X:number) // fuzzable relation

// Set operations
.decl AintersectionB(X:number) // fuzzable relation
.decl AunionB(X:number) // fuzzable relation
.decl AB(X:number) // fuzzable relation
.decl BMA(X:number) // fuzzable relation

// Cartesian product
.decl AxB(X:number, Y:number) // fuzzable relation

// Output all of them
.output AintersectionB
.output AunionB
.output AB
.output BMA
.output AxB

// A = {1, 2, 3, 4}
A(1).
A(2).
A(3).
A(4).

// B = {2, 3, 4, 5}
B(2).
B(3).
B(4).
B(5).


// Must be in both A and B
AintersectionB(X) :- A(X), B(X).

// Can be in A or B
AunionB(X) :- A(X).
AunionB(X) :- B(X).

// Must be in A and not B
AB(X) :- A(X), !B(X).

// Must be in B and not A
BMA(X) :- B(X), !A(X).

// Cartesian product of A and B (AxB), all the unique pairs where order matters
AxB(X, Y) :- A(X), B(Y).
