
.decl loop(i:number, x:number, y:number, z:number) // fuzzable relation
.decl R(a:number) // fuzzable relation
.output R()

loop(0, 0, 0, 0).
loop(1, 10, y, z) :- loop(0, _, y, z).
loop(2, x, y, z) :- loop(1, x, _, _), loop(0, _, y, z), x - z > 0.
loop(3, x, y, z*-1) :- loop(1, x, y, z), x - z <= 0.
loop(4, x, y, z) :- loop(2, x, y, z).
loop(4, x, y, z) :- loop(3, x, y, z).
R(z) :- loop(4, _, _, z), z >= 0.
