// Souffle - A Datalog Compiler


.type Day = Mon {} | Tue {} | Wed {} | Thu {} | Fri {} | Sat {} | San {} 

.decl DayBeforeInTheWeek(x: Day, y: Day) // fuzzable relation
.input DayBeforeInTheWeek



.decl BeforeInTheWeek(x: Day, y: Day) // fuzzable relation
BeforeInTheWeek(x, y) :- DayBeforeInTheWeek(x, y).
BeforeInTheWeek(x, z) :- DayBeforeInTheWeek(x, y), BeforeInTheWeek(y, z).
.output BeforeInTheWeek
