// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.decl numbers(x:number) // fuzzable relation
.decl result(x:number) // fuzzable relation

.output result()

numbers(-1).
numbers(1).
numbers(2).
numbers(3).
numbers(4).
numbers(5).

result(x) :- x = sum a : { numbers(a), a > 0 }.
