

.decl loop(line: number, x:number, y:number, z:number) // fuzzable relation
.decl Res(a:number) // fuzzable relation


loop(0, 0, 10, 100).

loop(1, x, y, z)   :- loop(0, x, y, z).
loop(1, x+1, y, z) :- loop(1, x, y, _), loop(0, _, _, z), x < y.

loop(2, x, y, z) :- loop(1, x, y, z), x >= y.
loop(2, x, y+1, z) :- loop(2, _, y, z), loop(1, x, _, _),  y < z.

loop(3, x, y, z) :- loop(2, x, y, z), y >= z.
Res(y) :- loop(3, _, y, _), y = 100.
