//
// double_tree.dl
//
// This test is useful in the analysis of the topological order
// of nodes. Use the debug report to view the scc graph, then
// see what order the nodes are visited in.

.decl xy(z:number) // fuzzable relation
.output xy()

.decl x1(z:number) // fuzzable relation
.decl x2(z:number) // fuzzable relation

.decl x11(z:number) // fuzzable relation
.decl x12(z:number) // fuzzable relation
.decl x13(z:number) // fuzzable relation

.decl x21(z:number) // fuzzable relation
.decl x22(z:number) // fuzzable relation
.decl x23(z:number) // fuzzable relation

.decl x111(z:number) // fuzzable relation
.decl x112(z:number) // fuzzable relation
.decl x113(z:number) // fuzzable relation
.decl x114(z:number) // fuzzable relation

.decl x121(z:number) // fuzzable relation
.decl x122(z:number) // fuzzable relation
.decl x123(z:number) // fuzzable relation
.decl x124(z:number) // fuzzable relation

.decl x131(z:number) // fuzzable relation
.decl x132(z:number) // fuzzable relation
.decl x133(z:number) // fuzzable relation
.decl x134(z:number) // fuzzable relation

.decl x211(z:number) // fuzzable relation
.decl x212(z:number) // fuzzable relation
.decl x213(z:number) // fuzzable relation
.decl x214(z:number) // fuzzable relation

.decl x221(z:number) // fuzzable relation
.decl x222(z:number) // fuzzable relation
.decl x223(z:number) // fuzzable relation
.decl x224(z:number) // fuzzable relation

.decl x231(z:number) // fuzzable relation
.decl x232(z:number) // fuzzable relation
.decl x233(z:number) // fuzzable relation
.decl x234(z:number) // fuzzable relation

.decl x1111(z:number) // fuzzable relation
.decl x1112(z:number) // fuzzable relation
.decl x1113(z:number) // fuzzable relation
.decl x1114(z:number) // fuzzable relation
.decl x1115(z:number) // fuzzable relation
.decl x1121(z:number) // fuzzable relation
.decl x1122(z:number) // fuzzable relation
.decl x1123(z:number) // fuzzable relation
.decl x1124(z:number) // fuzzable relation
.decl x1125(z:number) // fuzzable relation
.decl x1131(z:number) // fuzzable relation
.decl x1132(z:number) // fuzzable relation
.decl x1133(z:number) // fuzzable relation
.decl x1134(z:number) // fuzzable relation
.decl x1135(z:number) // fuzzable relation
.decl x1141(z:number) // fuzzable relation
.decl x1142(z:number) // fuzzable relation
.decl x1143(z:number) // fuzzable relation
.decl x1144(z:number) // fuzzable relation
.decl x1145(z:number) // fuzzable relation

.decl x1211(z:number) // fuzzable relation
.decl x1212(z:number) // fuzzable relation
.decl x1213(z:number) // fuzzable relation
.decl x1214(z:number) // fuzzable relation
.decl x1215(z:number) // fuzzable relation
.decl x1221(z:number) // fuzzable relation
.decl x1222(z:number) // fuzzable relation
.decl x1223(z:number) // fuzzable relation
.decl x1224(z:number) // fuzzable relation
.decl x1225(z:number) // fuzzable relation
.decl x1231(z:number) // fuzzable relation
.decl x1232(z:number) // fuzzable relation
.decl x1233(z:number) // fuzzable relation
.decl x1234(z:number) // fuzzable relation
.decl x1235(z:number) // fuzzable relation
.decl x1241(z:number) // fuzzable relation
.decl x1242(z:number) // fuzzable relation
.decl x1243(z:number) // fuzzable relation
.decl x1244(z:number) // fuzzable relation
.decl x1245(z:number) // fuzzable relation

.decl x1311(z:number) // fuzzable relation
.decl x1312(z:number) // fuzzable relation
.decl x1313(z:number) // fuzzable relation
.decl x1314(z:number) // fuzzable relation
.decl x1315(z:number) // fuzzable relation
.decl x1321(z:number) // fuzzable relation
.decl x1322(z:number) // fuzzable relation
.decl x1323(z:number) // fuzzable relation
.decl x1324(z:number) // fuzzable relation
.decl x1325(z:number) // fuzzable relation
.decl x1331(z:number) // fuzzable relation
.decl x1332(z:number) // fuzzable relation
.decl x1333(z:number) // fuzzable relation
.decl x1334(z:number) // fuzzable relation
.decl x1335(z:number) // fuzzable relation
.decl x1341(z:number) // fuzzable relation
.decl x1342(z:number) // fuzzable relation
.decl x1343(z:number) // fuzzable relation
.decl x1344(z:number) // fuzzable relation
.decl x1345(z:number) // fuzzable relation

.decl x2111(z:number) // fuzzable relation
.decl x2112(z:number) // fuzzable relation
.decl x2113(z:number) // fuzzable relation
.decl x2114(z:number) // fuzzable relation
.decl x2115(z:number) // fuzzable relation
.decl x2121(z:number) // fuzzable relation
.decl x2122(z:number) // fuzzable relation
.decl x2123(z:number) // fuzzable relation
.decl x2124(z:number) // fuzzable relation
.decl x2125(z:number) // fuzzable relation
.decl x2131(z:number) // fuzzable relation
.decl x2132(z:number) // fuzzable relation
.decl x2133(z:number) // fuzzable relation
.decl x2134(z:number) // fuzzable relation
.decl x2135(z:number) // fuzzable relation
.decl x2141(z:number) // fuzzable relation
.decl x2142(z:number) // fuzzable relation
.decl x2143(z:number) // fuzzable relation
.decl x2144(z:number) // fuzzable relation
.decl x2145(z:number) // fuzzable relation

.decl x2211(z:number) // fuzzable relation
.decl x2212(z:number) // fuzzable relation
.decl x2213(z:number) // fuzzable relation
.decl x2214(z:number) // fuzzable relation
.decl x2215(z:number) // fuzzable relation
.decl x2221(z:number) // fuzzable relation
.decl x2222(z:number) // fuzzable relation
.decl x2223(z:number) // fuzzable relation
.decl x2224(z:number) // fuzzable relation
.decl x2225(z:number) // fuzzable relation
.decl x2231(z:number) // fuzzable relation
.decl x2232(z:number) // fuzzable relation
.decl x2233(z:number) // fuzzable relation
.decl x2234(z:number) // fuzzable relation
.decl x2235(z:number) // fuzzable relation
.decl x2241(z:number) // fuzzable relation
.decl x2242(z:number) // fuzzable relation
.decl x2243(z:number) // fuzzable relation
.decl x2244(z:number) // fuzzable relation
.decl x2245(z:number) // fuzzable relation

.decl x2311(z:number) // fuzzable relation
.decl x2312(z:number) // fuzzable relation
.decl x2313(z:number) // fuzzable relation
.decl x2314(z:number) // fuzzable relation
.decl x2315(z:number) // fuzzable relation
.decl x2321(z:number) // fuzzable relation
.decl x2322(z:number) // fuzzable relation
.decl x2323(z:number) // fuzzable relation
.decl x2324(z:number) // fuzzable relation
.decl x2325(z:number) // fuzzable relation
.decl x2331(z:number) // fuzzable relation
.decl x2332(z:number) // fuzzable relation
.decl x2333(z:number) // fuzzable relation
.decl x2334(z:number) // fuzzable relation
.decl x2335(z:number) // fuzzable relation
.decl x2341(z:number) // fuzzable relation
.decl x2342(z:number) // fuzzable relation
.decl x2343(z:number) // fuzzable relation
.decl x2344(z:number) // fuzzable relation
.decl x2345(z:number) // fuzzable relation
.input x2345()

xy(z) :- x1(z), x2(z).

x1(z) :- x11(z), x12(z), x13(z).
x2(z) :- x21(z), x22(z), x23(z).

x11(z) :- x111(z), x112(z), x113(z), x114(z).
x12(z) :- x121(z), x122(z), x123(z), x124(z).
x13(z) :- x131(z), x132(z), x133(z), x134(z).

x21(z) :- x211(z), x212(z), x213(z), x214(z).
x22(z) :- x221(z), x222(z), x223(z), x224(z).
x23(z) :- x231(z), x232(z), x233(z), x234(z).

x111(z) :- x1111(z), x1112(z), x1113(z), x1114(z), x1115(z).
x112(z) :- x1121(z), x1122(z), x1123(z), x1124(z), x1125(z).
x113(z) :- x1131(z), x1132(z), x1133(z), x1134(z), x1135(z).
x114(z) :- x1141(z), x1142(z), x1143(z), x1144(z), x1145(z).

x121(z) :- x1211(z), x1212(z), x1213(z), x1214(z), x1215(z).
x122(z) :- x1221(z), x1222(z), x1223(z), x1224(z), x1225(z).
x123(z) :- x1231(z), x1232(z), x1233(z), x1234(z), x1235(z).
x124(z) :- x1241(z), x1242(z), x1243(z), x1244(z), x1245(z).

x131(z) :- x1311(z), x1312(z), x1313(z), x1314(z), x1315(z).
x132(z) :- x1321(z), x1322(z), x1323(z), x1324(z), x1325(z).
x133(z) :- x1331(z), x1332(z), x1333(z), x1334(z), x1335(z).
x134(z) :- x1341(z), x1342(z), x1343(z), x1344(z), x1345(z).

x211(z) :- x2111(z), x2112(z), x2113(z), x2114(z), x2115(z).
x212(z) :- x2121(z), x2122(z), x2123(z), x2124(z), x2125(z).
x213(z) :- x2131(z), x2132(z), x2133(z), x2134(z), x2135(z).
x214(z) :- x2141(z), x2142(z), x2143(z), x2144(z), x2145(z).

x221(z) :- x2211(z), x2212(z), x2213(z), x2214(z), x2215(z).
x222(z) :- x2221(z), x2222(z), x2223(z), x2224(z), x2225(z).
x223(z) :- x2231(z), x2232(z), x2233(z), x2234(z), x2235(z).
x224(z) :- x2241(z), x2242(z), x2243(z), x2244(z), x2245(z).

x231(z) :- x2311(z), x2312(z), x2313(z), x2314(z), x2315(z).
x232(z) :- x2321(z), x2322(z), x2323(z), x2324(z), x2325(z).
x233(z) :- x2331(z), x2332(z), x2333(z), x2334(z), x2335(z).
x234(z) :- x2341(z), x2342(z), x2343(z), x2344(z), x2345(z).

x1111(1).
x1112(1).
x1113(1).
x1114(1).
x1115(1).
x1121(1).
x1122(1).
x1123(1).
x1124(1).
x1125(1).
x1131(1).
x1132(1).
x1133(1).
x1134(1).
x1135(1).
x1141(1).
x1142(1).
x1143(1).
x1144(1).
x1145(1).

x1211(1).
x1212(1).
x1213(1).
x1214(1).
x1215(1).
x1221(1).
x1222(1).
x1223(1).
x1224(1).
x1225(1).
x1231(1).
x1232(1).
x1233(1).
x1234(1).
x1235(1).
x1241(1).
x1242(1).
x1243(1).
x1244(1).
x1245(1).

x1311(1).
x1312(1).
x1313(1).
x1314(1).
x1315(1).
x1321(1).
x1322(1).
x1323(1).
x1324(1).
x1325(1).
x1331(1).
x1332(1).
x1333(1).
x1334(1).
x1335(1).
x1341(1).
x1342(1).
x1343(1).
x1344(1).
x1345(1).

x2111(1).
x2112(1).
x2113(1).
x2114(1).
x2115(1).
x2121(1).
x2122(1).
x2123(1).
x2124(1).
x2125(1).
x2131(1).
x2132(1).
x2133(1).
x2134(1).
x2135(1).
x2141(1).
x2142(1).
x2143(1).
x2144(1).
x2145(1).

x2211(1).
x2212(1).
x2213(1).
x2214(1).
x2215(1).
x2221(1).
x2222(1).
x2223(1).
x2224(1).
x2225(1).
x2231(1).
x2232(1).
x2233(1).
x2234(1).
x2235(1).
x2241(1).
x2242(1).
x2243(1).
x2244(1).
x2245(1).

x2311(1).
x2312(1).
x2313(1).
x2314(1).
x2315(1).
x2321(1).
x2322(1).
x2323(1).
x2324(1).
x2325(1).
x2331(1).
x2332(1).
x2333(1).
x2334(1).
x2335(1).
x2341(1).
x2342(1).
x2343(1).
x2344(1).


.decl y1(z:number) // fuzzable relation
.decl y2(z:number) // fuzzable relation

.decl y11(z:number) // fuzzable relation
.decl y12(z:number) // fuzzable relation
.decl y13(z:number) // fuzzable relation

.decl y21(z:number) // fuzzable relation
.decl y22(z:number) // fuzzable relation
.decl y23(z:number) // fuzzable relation

.decl y111(z:number) // fuzzable relation
.decl y112(z:number) // fuzzable relation
.decl y113(z:number) // fuzzable relation
.decl y114(z:number) // fuzzable relation

.decl y121(z:number) // fuzzable relation
.decl y122(z:number) // fuzzable relation
.decl y123(z:number) // fuzzable relation
.decl y124(z:number) // fuzzable relation

.decl y131(z:number) // fuzzable relation
.decl y132(z:number) // fuzzable relation
.decl y133(z:number) // fuzzable relation
.decl y134(z:number) // fuzzable relation

.decl y211(z:number) // fuzzable relation
.decl y212(z:number) // fuzzable relation
.decl y213(z:number) // fuzzable relation
.decl y214(z:number) // fuzzable relation

.decl y221(z:number) // fuzzable relation
.decl y222(z:number) // fuzzable relation
.decl y223(z:number) // fuzzable relation
.decl y224(z:number) // fuzzable relation

.decl y231(z:number) // fuzzable relation
.decl y232(z:number) // fuzzable relation
.decl y233(z:number) // fuzzable relation
.decl y234(z:number) // fuzzable relation

.decl y1111(z:number) // fuzzable relation
.decl y1112(z:number) // fuzzable relation
.decl y1113(z:number) // fuzzable relation
.decl y1114(z:number) // fuzzable relation
.decl y1115(z:number) // fuzzable relation
.decl y1121(z:number) // fuzzable relation
.decl y1122(z:number) // fuzzable relation
.decl y1123(z:number) // fuzzable relation
.decl y1124(z:number) // fuzzable relation
.decl y1125(z:number) // fuzzable relation
.decl y1131(z:number) // fuzzable relation
.decl y1132(z:number) // fuzzable relation
.decl y1133(z:number) // fuzzable relation
.decl y1134(z:number) // fuzzable relation
.decl y1135(z:number) // fuzzable relation
.decl y1141(z:number) // fuzzable relation
.decl y1142(z:number) // fuzzable relation
.decl y1143(z:number) // fuzzable relation
.decl y1144(z:number) // fuzzable relation
.decl y1145(z:number) // fuzzable relation

.decl y1211(z:number) // fuzzable relation
.decl y1212(z:number) // fuzzable relation
.decl y1213(z:number) // fuzzable relation
.decl y1214(z:number) // fuzzable relation
.decl y1215(z:number) // fuzzable relation
.decl y1221(z:number) // fuzzable relation
.decl y1222(z:number) // fuzzable relation
.decl y1223(z:number) // fuzzable relation
.decl y1224(z:number) // fuzzable relation
.decl y1225(z:number) // fuzzable relation
.decl y1231(z:number) // fuzzable relation
.decl y1232(z:number) // fuzzable relation
.decl y1233(z:number) // fuzzable relation
.decl y1234(z:number) // fuzzable relation
.decl y1235(z:number) // fuzzable relation
.decl y1241(z:number) // fuzzable relation
.decl y1242(z:number) // fuzzable relation
.decl y1243(z:number) // fuzzable relation
.decl y1244(z:number) // fuzzable relation
.decl y1245(z:number) // fuzzable relation

.decl y1311(z:number) // fuzzable relation
.decl y1312(z:number) // fuzzable relation
.decl y1313(z:number) // fuzzable relation
.decl y1314(z:number) // fuzzable relation
.decl y1315(z:number) // fuzzable relation
.decl y1321(z:number) // fuzzable relation
.decl y1322(z:number) // fuzzable relation
.decl y1323(z:number) // fuzzable relation
.decl y1324(z:number) // fuzzable relation
.decl y1325(z:number) // fuzzable relation
.decl y1331(z:number) // fuzzable relation
.decl y1332(z:number) // fuzzable relation
.decl y1333(z:number) // fuzzable relation
.decl y1334(z:number) // fuzzable relation
.decl y1335(z:number) // fuzzable relation
.decl y1341(z:number) // fuzzable relation
.decl y1342(z:number) // fuzzable relation
.decl y1343(z:number) // fuzzable relation
.decl y1344(z:number) // fuzzable relation
.decl y1345(z:number) // fuzzable relation

.decl y2111(z:number) // fuzzable relation
.decl y2112(z:number) // fuzzable relation
.decl y2113(z:number) // fuzzable relation
.decl y2114(z:number) // fuzzable relation
.decl y2115(z:number) // fuzzable relation
.decl y2121(z:number) // fuzzable relation
.decl y2122(z:number) // fuzzable relation
.decl y2123(z:number) // fuzzable relation
.decl y2124(z:number) // fuzzable relation
.decl y2125(z:number) // fuzzable relation
.decl y2131(z:number) // fuzzable relation
.decl y2132(z:number) // fuzzable relation
.decl y2133(z:number) // fuzzable relation
.decl y2134(z:number) // fuzzable relation
.decl y2135(z:number) // fuzzable relation
.decl y2141(z:number) // fuzzable relation
.decl y2142(z:number) // fuzzable relation
.decl y2143(z:number) // fuzzable relation
.decl y2144(z:number) // fuzzable relation
.decl y2145(z:number) // fuzzable relation

.decl y2211(z:number) // fuzzable relation
.decl y2212(z:number) // fuzzable relation
.decl y2213(z:number) // fuzzable relation
.decl y2214(z:number) // fuzzable relation
.decl y2215(z:number) // fuzzable relation
.decl y2221(z:number) // fuzzable relation
.decl y2222(z:number) // fuzzable relation
.decl y2223(z:number) // fuzzable relation
.decl y2224(z:number) // fuzzable relation
.decl y2225(z:number) // fuzzable relation
.decl y2231(z:number) // fuzzable relation
.decl y2232(z:number) // fuzzable relation
.decl y2233(z:number) // fuzzable relation
.decl y2234(z:number) // fuzzable relation
.decl y2235(z:number) // fuzzable relation
.decl y2241(z:number) // fuzzable relation
.decl y2242(z:number) // fuzzable relation
.decl y2243(z:number) // fuzzable relation
.decl y2244(z:number) // fuzzable relation
.decl y2245(z:number) // fuzzable relation

.decl y2311(z:number) // fuzzable relation
.decl y2312(z:number) // fuzzable relation
.decl y2313(z:number) // fuzzable relation
.decl y2314(z:number) // fuzzable relation
.decl y2315(z:number) // fuzzable relation
.decl y2321(z:number) // fuzzable relation
.decl y2322(z:number) // fuzzable relation
.decl y2323(z:number) // fuzzable relation
.decl y2324(z:number) // fuzzable relation
.decl y2325(z:number) // fuzzable relation
.decl y2331(z:number) // fuzzable relation
.decl y2332(z:number) // fuzzable relation
.decl y2333(z:number) // fuzzable relation
.decl y2334(z:number) // fuzzable relation
.decl y2335(z:number) // fuzzable relation
.decl y2341(z:number) // fuzzable relation
.decl y2342(z:number) // fuzzable relation
.decl y2343(z:number) // fuzzable relation
.decl y2344(z:number) // fuzzable relation
.decl y2345(z:number) // fuzzable relation
.input y2345()

y1(z) :- xy(z).
y2(z) :- xy(z).

y11(z) :- y1(z).
y12(z) :- y1(z).
y13(z) :- y1(z).
y21(z) :- y2(z).
y22(z) :- y2(z).
y23(z) :- y2(z).

y111(z) :- y11(z).
y112(z) :- y11(z).
y113(z) :- y11(z).
y114(z) :- y11(z).
y121(z) :- y12(z).
y122(z) :- y12(z).
y123(z) :- y12(z).
y124(z) :- y12(z).
y131(z) :- y13(z).
y132(z) :- y13(z).
y133(z) :- y13(z).
y134(z) :- y13(z).

y211(z) :- y21(z).
y212(z) :- y21(z).
y213(z) :- y21(z).
y214(z) :- y21(z).
y221(z) :- y22(z).
y222(z) :- y22(z).
y223(z) :- y22(z).
y224(z) :- y22(z).
y231(z) :- y23(z).
y232(z) :- y23(z).
y233(z) :- y23(z).
y234(z) :- y23(z).

y1111(z) :- y111(z).
y1112(z) :- y111(z).
y1113(z) :- y111(z).
y1114(z) :- y111(z).
y1115(z) :- y111(z).
y1121(z) :- y112(z).
y1122(z) :- y112(z).
y1123(z) :- y112(z).
y1124(z) :- y112(z).
y1125(z) :- y112(z).
y1131(z) :- y113(z).
y1132(z) :- y113(z).
y1133(z) :- y113(z).
y1134(z) :- y113(z).
y1135(z) :- y113(z).
y1141(z) :- y114(z).
y1142(z) :- y114(z).
y1143(z) :- y114(z).
y1144(z) :- y114(z).
y1145(z) :- y114(z).

y1211(z) :- y121(z).
y1212(z) :- y121(z).
y1213(z) :- y121(z).
y1214(z) :- y121(z).
y1215(z) :- y121(z).
y1221(z) :- y122(z).
y1222(z) :- y122(z).
y1223(z) :- y122(z).
y1224(z) :- y122(z).
y1225(z) :- y122(z).
y1231(z) :- y123(z).
y1232(z) :- y123(z).
y1233(z) :- y123(z).
y1234(z) :- y123(z).
y1235(z) :- y123(z).
y1241(z) :- y124(z).
y1242(z) :- y124(z).
y1243(z) :- y124(z).
y1244(z) :- y124(z).
y1245(z) :- y124(z).

y1311(z) :- y131(z).
y1312(z) :- y131(z).
y1313(z) :- y131(z).
y1314(z) :- y131(z).
y1315(z) :- y131(z).
y1321(z) :- y132(z).
y1322(z) :- y132(z).
y1323(z) :- y132(z).
y1324(z) :- y132(z).
y1325(z) :- y132(z).
y1331(z) :- y133(z).
y1332(z) :- y133(z).
y1333(z) :- y133(z).
y1334(z) :- y133(z).
y1335(z) :- y133(z).
y1341(z) :- y134(z).
y1342(z) :- y134(z).
y1343(z) :- y134(z).
y1344(z) :- y134(z).
y1345(z) :- y134(z).
y2111(z) :- y211(z).

y2112(z) :- y211(z).
y2113(z) :- y211(z).
y2114(z) :- y211(z).
y2115(z) :- y211(z).
y2121(z) :- y212(z).
y2122(z) :- y212(z).
y2123(z) :- y212(z).
y2124(z) :- y212(z).
y2125(z) :- y212(z).
y2131(z) :- y213(z).
y2132(z) :- y213(z).
y2133(z) :- y213(z).
y2134(z) :- y213(z).
y2135(z) :- y213(z).
y2141(z) :- y214(z).
y2142(z) :- y214(z).
y2143(z) :- y214(z).
y2144(z) :- y214(z).
y2145(z) :- y214(z).

y2211(z) :- y221(z).
y2212(z) :- y221(z).
y2213(z) :- y221(z).
y2214(z) :- y221(z).
y2215(z) :- y221(z).
y2221(z) :- y222(z).
y2222(z) :- y222(z).
y2223(z) :- y222(z).
y2224(z) :- y222(z).
y2225(z) :- y222(z).
y2231(z) :- y223(z).
y2232(z) :- y223(z).
y2233(z) :- y223(z).
y2234(z) :- y223(z).
y2235(z) :- y223(z).
y2241(z) :- y224(z).
y2242(z) :- y224(z).
y2243(z) :- y224(z).
y2244(z) :- y224(z).
y2245(z) :- y224(z).

y2311(z) :- y231(z).
y2312(z) :- y231(z).
y2313(z) :- y231(z).
y2314(z) :- y231(z).
y2315(z) :- y231(z).
y2321(z) :- y232(z).
y2322(z) :- y232(z).
y2323(z) :- y232(z).
y2324(z) :- y232(z).
y2325(z) :- y232(z).
y2331(z) :- y233(z).
y2332(z) :- y233(z).
y2333(z) :- y233(z).
y2334(z) :- y233(z).
y2335(z) :- y233(z).
y2341(z) :- y234(z).
y2342(z) :- y234(z).
y2343(z) :- y234(z).
y2344(z) :- y234(z).
y2345(z) :- y234(z).
