.decl Element(value:number) // fuzzable relation
.decl TotalValue(value:number) // fuzzable relation
.decl Average(value:number) // fuzzable relation
.decl NumberOfelements(value:number) // fuzzable relation



Element(1).
Element(2).
Element(7).
Element(25).
Element(104).



TotalValue(value) :- value= sum ElementValue : Element(ElementValue).

NumberOfelements(value) :- value= count : Element(_).

Average(f/d) :- TotalValue(f), NumberOfelements(d).
