.type n <: number

.decl A (x:n, y:n) // fuzzable relation
.output A ()
.decl B (x:n, y:n) // fuzzable relation
.output B ()
.decl C (x:n, y:n) // fuzzable relation
.output C ()
.decl D (x:n, y:n) // fuzzable relation
.output D ()
.decl E (x:n, y:n) // fuzzable relation
.output E ()
.decl F (x:n, y:n) // fuzzable relation
.output F ()
.decl S (x:n, y:n) // fuzzable relation
.output S ()
.decl N (x:n) // fuzzable relation
.output N ()

N(0).
N(1).
N(2).
N(3).
N(4).
N(5).

S(x,y) :- N(x), N(y).

A(a,c) :- S(a,c), a > c.
B(a,c) :- S(a,c), a < c.
C(a,c) :- S(a,c), a = c.
D(a,c) :- S(a,c), a != c.
E(a,c) :- S(a,c), a <= c.
F(a,c) :- S(a,c), a >= c.

