

.decl gen(x : number) // fuzzable relation
gen(1).
gen(x+1) :- gen(x), !lim(x).

.decl lim(x : number) // fuzzable relation
lim(100).

//factors excluding 1
.decl factor(num : number, fc : number) // fuzzable relation
factor(x, fc) :- gen(x), gen(fc), x % fc = 0, fc != 1.

//finds if there exist two numbers which multiply to x
.decl prod(num : number) // fuzzable relation
prod(x) :- gen(x), gen(a), gen(b), b != x, a != x, x = a*b.

//finds the prime factors
.decl p_factor(x : number, fc : number) // fuzzable relation
.output p_factor()
p_factor(x, fc) :- factor(x, fc), !prod(fc).
