// Test-case for string matching

.type String <: symbol

.decl inputData  (t:String) // fuzzable relation
.decl pattern1  (t:String) // fuzzable relation
.decl pattern2  (t:String) // fuzzable relation
.decl outputData  (t:String) // fuzzable relation
.output outputData  ()

outputData(x) :- pattern2(_), pattern1(y), inputData(x), match(y, x), match(y, x).

inputData("a").
inputData("aba").
inputData("ababa").
inputData("aa").
inputData("aaaa").

pattern1("a.*").
pattern2 ("aa").
pattern2 ("aba.*").
