
.type R = [ x : number ]

.decl NumbersA(x : number) // fuzzable relation
.decl NumbersB(x : number) // fuzzable relation
.decl SymbolsA(x : symbol) 
.decl SymbolsB(x : symbol)
.decl RecordsA(x : R)
.decl RecordsB(x : R)
.decl CountNumbers(x : number) // fuzzable relation
.decl CountSymbols(x : number) // fuzzable relation
.decl CountRecords(x : number) // fuzzable relation

NumbersA(1).
NumbersB(2).
SymbolsA("a").
SymbolsA("b").
SymbolsB("b").
SymbolsB("c").
RecordsA([1]).
RecordsA([2]).
RecordsA([3]).
RecordsB([2]).
RecordsB([3]).
RecordsB([4]).
RecordsB([5]).
RecordsB(nil).

CountNumbers(x) :- x = count : { NumbersA(y), NumbersB(y) } .
CountSymbols(x) :- x = count : { SymbolsA(y), SymbolsB(y) } .
CountRecords(x) :- x = count : { RecordsA(y), RecordsB(y) } .

.output CountNumbers
.output CountSymbols
.output CountRecords
